# Generated by Django 4.1.9 on 2023-06-16 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("admin_page_states", "0001_initial"),
        ("admin_page_themes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("owner", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=200)),
                ("location_length", models.CharField(blank=True, default=0, max_length=200)),
                ("location_width", models.CharField(blank=True, default=0, max_length=200)),
                ("capacity", models.IntegerField()),
                ("created_date", models.DateField(auto_now_add=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("description", models.TextField(blank=True)),
                ("images", models.ImageField(upload_to="imagenes")),
                (
                    "state",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="admin_page_states.state"),
                ),
                (
                    "theme",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="admin_page_themes.theme"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpeningHour",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (1, "Lunes"),
                            (2, "Martes"),
                            (3, "Miércoles"),
                            (4, "Jueves"),
                            (5, "Viernes"),
                            (6, "Sábado"),
                            (7, "Domingo"),
                        ]
                    ),
                ),
                ("opening_time", models.TimeField()),
                ("closing_time", models.TimeField()),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_hours",
                        to="admin_page_locations.location",
                    ),
                ),
            ],
        ),
    ]
