# Generated by Django 4.1.9 on 2023-06-28 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("admin_page_states", "0001_initial"),
        ("admin_page_themes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("owner", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=200)),
                ("location_length", models.CharField(blank=True, max_length=200, null=True)),
                ("location_width", models.CharField(blank=True, max_length=200, null=True)),
                ("capacity", models.IntegerField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("description", models.TextField(blank=True)),
                ("web_site", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("parking", models.BooleanField(default=False)),
                (
                    "state",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="admin_page_states.state"),
                ),
                (
                    "theme",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="admin_page_themes.theme"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpeningHour",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "day_of_week",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Lunes"),
                            (2, "Martes"),
                            (3, "Miércoles"),
                            (4, "Jueves"),
                            (5, "Viernes"),
                            (6, "Sábado"),
                            (7, "Domingo"),
                        ],
                        null=True,
                    ),
                ),
                ("opening_time", models.TimeField(blank=True, null=True)),
                ("closing_time", models.TimeField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_hours",
                        to="admin_page_locations.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(blank=True, null=True, upload_to="location_images")),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="admin_page_locations.location",
                    ),
                ),
            ],
        ),
    ]
